### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Endle** [Endle/fireSeqSearch#22]
PLEASE DON'T COMMENT UNDER IT. Feel free to open a new issue for feedback, suggestion, brainstorming or anything else.

- [ ] Show search summary
- [x] https://github.com/Endle/fireSeqSearch/issues/27
- [x] https://github.com/Endle/fireSeqSearch/issues/24
- [ ] Fix https://github.com/Endle/fireSeqSearch/issues/13
- [ ] Refactor JS code for DOM operation. It blocks https://github.com/Endle/fireSeqSearch/issues/21
- [ ] ~~Publish this plugin on Edge~~
- [ ] ~~Support https://github.com/Endle/fireSeqSearch/issues/19~~
